import type { Recipe } from '@/types/recipe';
import { generateSlug } from '@/utils/helpers';

export const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Tavuklu Pilav',
    slug: generateSlug('Tavuklu Pilav'),
    ingredients: ['tavuk göğsü', 'pirinç', 'tereyağı', 'soğan', 'tuz', 'karabiber'],
    cookingTime: 35,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 2,
    name: 'Karnıyarık',
    slug: generateSlug('Karnıyarık'),
    ingredients: ['patlıcan', 'kıyma', 'soğan', 'domates', 'salça', 'sarımsak', 'zeytinyağı'],
    cookingTime: 60,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 3,
    name: 'Mercimek Çorbası',
    slug: generateSlug('Mercimek Çorbası'),
    ingredients: ['kırmızı mercimek', 'soğan', 'havuç', 'salça', 'zeytinyağı', 'un', 'tuz'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 4,
    name: 'Tavuk Fajitas',
    slug: generateSlug('Tavuk Fajitas'),
    ingredients: ['tavuk göğsü', 'biber', 'soğan', 'tortilla', 'baharatlar', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 5,
    name: 'Somon Teriyaki',
    slug: generateSlug('Somon Teriyaki'),
    ingredients: ['somon', 'soya sosu', 'bal', 'sarımsak', 'zencefil', 'susam'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Asya',
  },
  {
    id: 6,
    name: 'Spagetti Bolognese',
    slug: generateSlug('Spagetti Bolognese'),
    ingredients: ['spagetti', 'kıyma', 'domates', 'soğan', 'sarımsak', 'zeytinyağı'],
    cookingTime: 40,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 7,
    name: 'Tavuk Şiş',
    slug: generateSlug('Tavuk Şiş'),
    ingredients: ['tavuk göğsü', 'yoğurt', 'zeytinyağı', 'soğan', 'biber', 'baharatlar'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 8,
    name: 'Biftek',
    slug: generateSlug('Biftek'),
    ingredients: ['dana bonfile', 'tuz', 'karabiber', 'tereyağı', 'sarımsak'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 9,
    name: 'Tavuk Tikka Masala',
    slug: generateSlug('Tavuk Tikka Masala'),
    ingredients: ['tavuk', 'yoğurt', 'krema', 'domates', 'baharatlar', 'soğan'],
    cookingTime: 45,
    difficulty: 'orta',
    cuisine: 'Hint',
  },
  {
    id: 10,
    name: 'Kuru Fasulye',
    slug: generateSlug('Kuru Fasulye'),
    ingredients: ['kuru fasulye', 'et', 'soğan', 'salça', 'zeytinyağı', 'tuz'],
    cookingTime: 90,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 11,
    name: 'Izgara Somon',
    slug: generateSlug('Izgara Somon'),
    ingredients: ['somon', 'limon', 'zeytinyağı', 'tuz', 'karabiber', 'dereotu'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Akdeniz',
  },
  {
    id: 12,
    name: 'Menemen',
    slug: generateSlug('Menemen'),
    ingredients: ['yumurta', 'domates', 'biber', 'soğan', 'zeytinyağı', 'tuz'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 13,
    name: 'Tavuk Parmesan',
    slug: generateSlug('Tavuk Parmesan'),
    ingredients: ['tavuk göğsü', 'parmesan', 'domates sosu', 'mozzarella', 'ekmek kırığı'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'İtalyan',
  },
  {
    id: 14,
    name: 'Etli Nohut',
    slug: generateSlug('Etli Nohut'),
    ingredients: ['nohut', 'kuşbaşı et', 'soğan', 'salça', 'zeytinyağı', 'baharatlar'],
    cookingTime: 80,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 15,
    name: 'Tavuk Burrito',
    slug: generateSlug('Tavuk Burrito'),
    ingredients: ['tavuk', 'pirinç', 'fasulye', 'tortilla', 'peynir', 'salsa'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 16,
    name: 'Köfte',
    slug: generateSlug('Köfte'),
    ingredients: ['kıyma', 'soğan', 'ekmek içi', 'yumurta', 'baharatlar', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 17,
    name: 'Tavuk Alfredo',
    slug: generateSlug('Tavuk Alfredo'),
    ingredients: ['tavuk', 'fettuccine', 'krema', 'parmesan', 'tereyağı', 'sarımsak'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 18,
    name: 'Zeytinyağlı Fasulye',
    slug: generateSlug('Zeytinyağlı Fasulye'),
    ingredients: ['taze fasulye', 'domates', 'soğan', 'zeytinyağı', 'şeker', 'tuz'],
    cookingTime: 45,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 19,
    name: 'Somon Poke Bowl',
    slug: generateSlug('Somon Poke Bowl'),
    ingredients: ['somon', 'pirinç', 'avokado', 'salatalık', 'soya sosu', 'susam'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Asya',
  },
  {
    id: 20,
    name: 'Tavuk Sote',
    slug: generateSlug('Tavuk Sote'),
    ingredients: ['tavuk göğsü', 'biber', 'domates', 'soğan', 'sarımsak', 'zeytinyağı'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 21,
    name: 'BBQ Tavuk',
    slug: generateSlug('BBQ Tavuk'),
    ingredients: ['tavuk but', 'bbq sos', 'bal', 'sarımsak tozu', 'zeytinyağı'],
    cookingTime: 40,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 22,
    name: 'Patlıcan Musakka',
    slug: generateSlug('Patlıcan Musakka'),
    ingredients: ['patlıcan', 'kıyma', 'domates', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 55,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 23,
    name: 'Tavuk Pad Thai',
    slug: generateSlug('Tavuk Pad Thai'),
    ingredients: ['pirinç eriştesi', 'tavuk', 'yumurta', 'fıstık', 'soya sosu', 'limon'],
    cookingTime: 25,
    difficulty: 'orta',
    cuisine: 'Asya',
  },
  {
    id: 24,
    name: 'Etli Bamya',
    slug: generateSlug('Etli Bamya'),
    ingredients: ['bamya', 'et', 'domates', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 60,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 25,
    name: 'Margherita Pizza',
    slug: generateSlug('Margherita Pizza'),
    ingredients: ['pizza hamuru', 'domates sosu', 'mozzarella', 'fesleğen', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 26,
    name: 'Tavuk Çorbası',
    slug: generateSlug('Tavuk Çorbası'),
    ingredients: ['tavuk', 'havuç', 'patates', 'un', 'yumurta', 'limon'],
    cookingTime: 40,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 27,
    name: 'Taco',
    slug: generateSlug('Taco'),
    ingredients: ['kıyma', 'taco kabuğu', 'marul', 'domates', 'peynir', 'salsa'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 28,
    name: 'İmam Bayıldı',
    slug: generateSlug('İmam Bayıldı'),
    ingredients: ['patlıcan', 'soğan', 'domates', 'sarımsak', 'zeytinyağı', 'maydanoz'],
    cookingTime: 50,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 29,
    name: 'Tavuk Quesadilla',
    slug: generateSlug('Tavuk Quesadilla'),
    ingredients: ['tavuk', 'tortilla', 'peynir', 'biber', 'soğan', 'zeytinyağı'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 30,
    name: 'Somon Salata',
    slug: generateSlug('Somon Salata'),
    ingredients: ['somon', 'marul', 'domates', 'salatalık', 'limon', 'zeytinyağı'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Akdeniz',
  },
  {
    id: 31,
    name: 'Yaprak Sarma',
    slug: generateSlug('Yaprak Sarma'),
    ingredients: ['asma yaprağı', 'pirinç', 'kıyma', 'soğan', 'zeytinyağı', 'nane'],
    cookingTime: 70,
    difficulty: 'zor',
    cuisine: 'Türk',
  },
  {
    id: 32,
    name: 'Hamburger',
    slug: generateSlug('Hamburger'),
    ingredients: ['kıyma', 'ekmek', 'marul', 'domates', 'peynir', 'soğan'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 33,
    name: 'Tavuk Stir Fry',
    slug: generateSlug('Tavuk Stir Fry'),
    ingredients: ['tavuk', 'brokoli', 'havuç', 'soya sosu', 'sarımsak', 'pirinç'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Asya',
  },
  {
    id: 34,
    name: 'Ispanaklı Börek',
    slug: generateSlug('Ispanaklı Börek'),
    ingredients: ['yufka', 'ıspanak', 'soğan', 'peynir', 'yumurta', 'zeytinyağı'],
    cookingTime: 40,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 35,
    name: 'Penne Arrabiata',
    slug: generateSlug('Penne Arrabiata'),
    ingredients: ['penne', 'domates', 'sarımsak', 'acı biber', 'zeytinyağı', 'fesleğen'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 36,
    name: 'Etli Biber Dolması',
    slug: generateSlug('Etli Biber Dolması'),
    ingredients: ['biber', 'kıyma', 'pirinç', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 50,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 37,
    name: 'Caesar Salata',
    slug: generateSlug('Caesar Salata'),
    ingredients: ['marul', 'tavuk', 'kruton', 'parmesan', 'caesar sos'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 38,
    name: 'Zeytinyağlı Enginar',
    slug: generateSlug('Zeytinyağlı Enginar'),
    ingredients: ['enginar', 'havuç', 'bezelye', 'soğan', 'zeytinyağı', 'limon'],
    cookingTime: 45,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 39,
    name: 'Tavuk Schnitzel',
    slug: generateSlug('Tavuk Schnitzel'),
    ingredients: ['tavuk göğsü', 'ekmek kırığı', 'yumurta', 'un', 'zeytinyağı', 'limon'],
    cookingTime: 25,
    difficulty: 'orta',
    cuisine: 'Alman',
  },
  {
    id: 40,
    name: 'Tavuk Döner',
    slug: generateSlug('Tavuk Döner'),
    ingredients: ['tavuk but', 'yoğurt', 'salça', 'zeytinyağı', 'baharatlar'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 41,
    name: 'Somon Burger',
    slug: generateSlug('Somon Burger'),
    ingredients: ['somon', 'ekmek', 'marul', 'domates', 'sos', 'soğan'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 42,
    name: 'Etli Lahana Sarma',
    slug: generateSlug('Etli Lahana Sarma'),
    ingredients: ['lahana', 'kıyma', 'pirinç', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 80,
    difficulty: 'zor',
    cuisine: 'Türk',
  },
  {
    id: 43,
    name: 'Tavuk Enchilada',
    slug: generateSlug('Tavuk Enchilada'),
    ingredients: ['tavuk', 'tortilla', 'enchilada sos', 'peynir', 'soğan'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'Meksika',
  },
  {
    id: 44,
    name: 'Patlıcan Kızartma',
    slug: generateSlug('Patlıcan Kızartma'),
    ingredients: ['patlıcan', 'zeytinyağı', 'yoğurt', 'sarımsak', 'tuz'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 45,
    name: 'Risotto',
    slug: generateSlug('Risotto'),
    ingredients: ['arborio pirinç', 'tavuk suyu', 'parmesan', 'soğan', 'beyaz şarap', 'tereyağı'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'İtalyan',
  },
  {
    id: 46,
    name: 'Zeytinyağlı Pırasa',
    slug: generateSlug('Zeytinyağlı Pırasa'),
    ingredients: ['pırasa', 'havuç', 'pirinç', 'zeytinyağı', 'şeker', 'limon'],
    cookingTime: 40,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 47,
    name: 'Tavuk Katsu',
    slug: generateSlug('Tavuk Katsu'),
    ingredients: ['tavuk göğsü', 'panko', 'yumurta', 'un', 'zeytinyağı', 'katsu sos'],
    cookingTime: 25,
    difficulty: 'orta',
    cuisine: 'Japon',
  },
  {
    id: 48,
    name: 'Bulgur Pilavı',
    slug: generateSlug('Bulgur Pilavı'),
    ingredients: ['bulgur', 'domates', 'biber', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 49,
    name: 'Fish and Chips',
    slug: generateSlug('Fish and Chips'),
    ingredients: ['balık', 'patates', 'un', 'bira', 'zeytinyağı', 'tuz'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'İngiliz',
  },
  {
    id: 50,
    name: 'Tavuk Kapama',
    slug: generateSlug('Tavuk Kapama'),
    ingredients: ['tavuk', 'soğan', 'havuç', 'patates', 'zeytinyağı', 'baharatlar'],
    cookingTime: 60,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 51,
    name: 'Carbonara',
    slug: generateSlug('Carbonara'),
    ingredients: ['spagetti', 'yumurta', 'guanciale', 'parmesan', 'karabiber'],
    cookingTime: 20,
    difficulty: 'orta',
    cuisine: 'İtalyan',
  },
  {
    id: 52,
    name: 'Kabak Mücver',
    slug: generateSlug('Kabak Mücver'),
    ingredients: ['kabak', 'yumurta', 'un', 'peynir', 'dereotu', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 53,
    name: 'Tavuk Teriyaki',
    slug: generateSlug('Tavuk Teriyaki'),
    ingredients: ['tavuk', 'teriyaki sos', 'pirinç', 'brokoli', 'susam', 'zeytinyağı'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Japon',
  },
  {
    id: 54,
    name: 'Etli Kereviz',
    slug: generateSlug('Etli Kereviz'),
    ingredients: ['kereviz', 'et', 'havuç', 'soğan', 'limon', 'zeytinyağı'],
    cookingTime: 55,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 55,
    name: 'Biftek Salata',
    slug: generateSlug('Biftek Salata'),
    ingredients: ['biftek', 'marul', 'roka', 'domates', 'balzamik sirke', 'zeytinyağı'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 56,
    name: 'Domates Çorbası',
    slug: generateSlug('Domates Çorbası'),
    ingredients: ['domates', 'un', 'tereyağı', 'süt', 'tuz', 'şeker'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 57,
    name: 'Somon Teriyaki Bowl',
    slug: generateSlug('Somon Teriyaki Bowl'),
    ingredients: ['somon', 'pirinç', 'brokoli', 'havuç', 'teriyaki sos', 'susam'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Asya',
  },
  {
    id: 58,
    name: 'Kıymalı Börek',
    slug: generateSlug('Kıymalı Börek'),
    ingredients: ['yufka', 'kıyma', 'soğan', 'yumurta', 'süt', 'zeytinyağı'],
    cookingTime: 45,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 59,
    name: 'Tavuk Shawarma',
    slug: generateSlug('Tavuk Shawarma'),
    ingredients: ['tavuk', 'yoğurt', 'baharatlar', 'lavaş', 'domates', 'soğan'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Ortadoğu',
  },
  {
    id: 60,
    name: 'Zeytinyağlı Yaprak Sarma',
    slug: generateSlug('Zeytinyağlı Yaprak Sarma'),
    ingredients: ['asma yaprağı', 'pirinç', 'soğan', 'zeytinyağı', 'nane', 'limon'],
    cookingTime: 65,
    difficulty: 'zor',
    cuisine: 'Türk',
  },
  {
    id: 61,
    name: 'Tavuk Nugget',
    slug: generateSlug('Tavuk Nugget'),
    ingredients: ['tavuk göğsü', 'ekmek kırığı', 'yumurta', 'un', 'zeytinyağı', 'baharatlar'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 62,
    name: 'Etli Taze Fasulye',
    slug: generateSlug('Etli Taze Fasulye'),
    ingredients: ['taze fasulye', 'et', 'domates', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 60,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 63,
    name: 'Pesto Makarna',
    slug: generateSlug('Pesto Makarna'),
    ingredients: ['makarna', 'fesleğen', 'çam fıstığı', 'parmesan', 'sarımsak', 'zeytinyağı'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 64,
    name: 'Tavuk Pirzola',
    slug: generateSlug('Tavuk Pirzola'),
    ingredients: ['tavuk pirzola', 'zeytinyağı', 'limon', 'baharatlar', 'sarımsak'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 65,
    name: 'Biftek Fajitas',
    slug: generateSlug('Biftek Fajitas'),
    ingredients: ['biftek', 'biber', 'soğan', 'tortilla', 'baharatlar', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 66,
    name: 'Tavuk Güveç',
    slug: generateSlug('Tavuk Güveç'),
    ingredients: ['tavuk', 'patates', 'havuç', 'biber', 'domates', 'zeytinyağı'],
    cookingTime: 70,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 67,
    name: 'Somon Patates',
    slug: generateSlug('Somon Patates'),
    ingredients: ['somon', 'patates', 'zeytinyağı', 'limon', 'dereotu', 'tuz'],
    cookingTime: 35,
    difficulty: 'kolay',
    cuisine: 'Akdeniz',
  },
  {
    id: 68,
    name: 'Yoğurtlu Kabak',
    slug: generateSlug('Yoğurtlu Kabak'),
    ingredients: ['kabak', 'yoğurt', 'sarımsak', 'zeytinyağı', 'tuz'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 69,
    name: 'Tavuk Lo Mein',
    slug: generateSlug('Tavuk Lo Mein'),
    ingredients: ['eriște', 'tavuk', 'sebze', 'soya sosu', 'susam yağı', 'sarımsak'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Çin',
  },
  {
    id: 70,
    name: 'Etli Patlıcan',
    slug: generateSlug('Etli Patlıcan'),
    ingredients: ['patlıcan', 'kıyma', 'domates', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 55,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 71,
    name: 'Tavuk Caesar Wrap',
    slug: generateSlug('Tavuk Caesar Wrap'),
    ingredients: ['tavuk', 'tortilla', 'marul', 'parmesan', 'caesar sos'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 72,
    name: 'Tavuklu Erişte',
    slug: generateSlug('Tavuklu Erişte'),
    ingredients: ['erişte', 'tavuk', 'havuç', 'soğan', 'zeytinyağı', 'baharatlar'],
    cookingTime: 35,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 73,
    name: 'Biftek Stroganoff',
    slug: generateSlug('Biftek Stroganoff'),
    ingredients: ['biftek', 'mantar', 'soğan', 'krema', 'hardal', 'zeytinyağı'],
    cookingTime: 30,
    difficulty: 'orta',
    cuisine: 'Rus',
  },
  {
    id: 74,
    name: 'Zeytinyağlı Kabak',
    slug: generateSlug('Zeytinyağlı Kabak'),
    ingredients: ['kabak', 'domates', 'soğan', 'zeytinyağı', 'şeker', 'dereotu'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 75,
    name: 'Tavuk Ramen',
    slug: generateSlug('Tavuk Ramen'),
    ingredients: ['ramen', 'tavuk', 'yumurta', 'bok choy', 'tavuk suyu', 'soya sosu'],
    cookingTime: 40,
    difficulty: 'orta',
    cuisine: 'Japon',
  },
  {
    id: 76,
    name: 'Tavuk Haşlama',
    slug: generateSlug('Tavuk Haşlama'),
    ingredients: ['tavuk', 'havuç', 'patates', 'soğan', 'tuz', 'karabiber'],
    cookingTime: 50,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 77,
    name: 'Somon Sushi Bowl',
    slug: generateSlug('Somon Sushi Bowl'),
    ingredients: ['somon', 'sushi pirinci', 'avokado', 'salatalık', 'nori', 'soya sosu'],
    cookingTime: 25,
    difficulty: 'orta',
    cuisine: 'Japon',
  },
  {
    id: 78,
    name: 'Tavuklu Mantarlı Sote',
    slug: generateSlug('Tavuklu Mantarlı Sote'),
    ingredients: ['tavuk', 'mantar', 'soğan', 'krema', 'zeytinyağı', 'baharatlar'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 79,
    name: 'Biftek Chimichurri',
    slug: generateSlug('Biftek Chimichurri'),
    ingredients: ['biftek', 'maydanoz', 'sarımsak', 'sirke', 'zeytinyağı', 'acı biber'],
    cookingTime: 25,
    difficulty: 'orta',
    cuisine: 'Arjantin',
  },
  {
    id: 80,
    name: 'Patlıcan Salatası',
    slug: generateSlug('Patlıcan Salatası'),
    ingredients: ['patlıcan', 'yoğurt', 'sarımsak', 'zeytinyağı', 'limon', 'maydanoz'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 81,
    name: 'Tavuk Souvlaki',
    slug: generateSlug('Tavuk Souvlaki'),
    ingredients: ['tavuk', 'limon', 'zeytinyağı', 'oregano', 'sarımsak', 'pita'],
    cookingTime: 30,
    difficulty: 'kolay',
    cuisine: 'Yunan',
  },
  {
    id: 82,
    name: 'Kıymalı Pide',
    slug: generateSlug('Kıymalı Pide'),
    ingredients: ['hamur', 'kıyma', 'domates', 'biber', 'soğan', 'baharatlar'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 83,
    name: 'Somon Tacos',
    slug: generateSlug('Somon Tacos'),
    ingredients: ['somon', 'tortilla', 'lahana salatası', 'avokado', 'limon', 'krema'],
    cookingTime: 20,
    difficulty: 'kolay',
    cuisine: 'Meksika',
  },
  {
    id: 84,
    name: 'Tavuk Köri',
    slug: generateSlug('Tavuk Köri'),
    ingredients: ['tavuk', 'köri', 'krema', 'soğan', 'zeytinyağı', 'baharatlar'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'Hint',
  },
  {
    id: 85,
    name: 'Mantı',
    slug: generateSlug('Mantı'),
    ingredients: ['hamur', 'kıyma', 'yoğurt', 'sarımsak', 'tereyağı', 'nane'],
    cookingTime: 90,
    difficulty: 'zor',
    cuisine: 'Türk',
  },
  {
    id: 86,
    name: 'Tavuk Satay',
    slug: generateSlug('Tavuk Satay'),
    ingredients: ['tavuk', 'fıstık ezmesi', 'soya sosu', 'limon', 'baharatlar'],
    cookingTime: 30,
    difficulty: 'orta',
    cuisine: 'Asya',
  },
  {
    id: 87,
    name: 'Biftek Salad Bowl',
    slug: generateSlug('Biftek Salad Bowl'),
    ingredients: ['biftek', 'pirinç', 'sebze karışımı', 'avokado', 'limon', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 88,
    name: 'Sucuklu Yumurta',
    slug: generateSlug('Sucuklu Yumurta'),
    ingredients: ['sucuk', 'yumurta', 'zeytinyağı', 'tuz', 'karabiber'],
    cookingTime: 10,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 89,
    name: 'Somon Pasta',
    slug: generateSlug('Somon Pasta'),
    ingredients: ['somon', 'penne', 'krema', 'dereotu', 'limon', 'zeytinyağı'],
    cookingTime: 25,
    difficulty: 'kolay',
    cuisine: 'İtalyan',
  },
  {
    id: 90,
    name: 'Tavuk Wings',
    slug: generateSlug('Tavuk Wings'),
    ingredients: ['tavuk kanat', 'acı sos', 'bal', 'zeytinyağı', 'baharatlar'],
    cookingTime: 40,
    difficulty: 'kolay',
    cuisine: 'Amerikan',
  },
  {
    id: 91,
    name: 'Hünkar Beğendi',
    slug: generateSlug('Hünkar Beğendi'),
    ingredients: ['patlıcan', 'kuşbaşı et', 'süt', 'un', 'kaşar peyniri', 'tereyağı'],
    cookingTime: 70,
    difficulty: 'zor',
    cuisine: 'Türk',
  },
  {
    id: 92,
    name: 'Tavuk Cacciatore',
    slug: generateSlug('Tavuk Cacciatore'),
    ingredients: ['tavuk', 'domates', 'mantar', 'biber', 'zeytinyağı', 'kekik'],
    cookingTime: 50,
    difficulty: 'orta',
    cuisine: 'İtalyan',
  },
  {
    id: 93,
    name: 'Kumpir',
    slug: generateSlug('Kumpir'),
    ingredients: ['patates', 'tereyağı', 'kaşar', 'mısır', 'zeytin', 'turşu'],
    cookingTime: 60,
    difficulty: 'kolay',
    cuisine: 'Türk',
  },
  {
    id: 94,
    name: 'Somon Ceviche',
    slug: generateSlug('Somon Ceviche'),
    ingredients: ['somon', 'limon', 'soğan', 'biber', 'kişniş', 'zeytinyağı'],
    cookingTime: 20,
    difficulty: 'orta',
    cuisine: 'Peru',
  },
  {
    id: 95,
    name: 'Tavuk Gyros',
    slug: generateSlug('Tavuk Gyros'),
    ingredients: ['tavuk', 'yoğurt', 'sarımsak', 'pita', 'domates', 'soğan'],
    cookingTime: 35,
    difficulty: 'kolay',
    cuisine: 'Yunan',
  },
  {
    id: 96,
    name: 'Etli Kuru Patlıcan',
    slug: generateSlug('Etli Kuru Patlıcan'),
    ingredients: ['kuru patlıcan', 'kıyma', 'domates', 'soğan', 'salça', 'zeytinyağı'],
    cookingTime: 65,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 97,
    name: 'Tavuk Marsala',
    slug: generateSlug('Tavuk Marsala'),
    ingredients: ['tavuk', 'mantar', 'marsala şarabı', 'krema', 'zeytinyağı', 'un'],
    cookingTime: 35,
    difficulty: 'orta',
    cuisine: 'İtalyan',
  },
  {
    id: 98,
    name: 'Lahmacun',
    slug: generateSlug('Lahmacun'),
    ingredients: ['hamur', 'kıyma', 'domates', 'biber', 'soğan', 'maydanoz'],
    cookingTime: 30,
    difficulty: 'orta',
    cuisine: 'Türk',
  },
  {
    id: 99,
    name: 'Somon Sashimi Bowl',
    slug: generateSlug('Somon Sashimi Bowl'),
    ingredients: ['somon', 'pirinç', 'edamame', 'avokado', 'soya sosu', 'wasabi'],
    cookingTime: 15,
    difficulty: 'kolay',
    cuisine: 'Japon',
  },
  {
    id: 100,
    name: 'Tavuk Cordon Bleu',
    slug: generateSlug('Tavuk Cordon Bleu'),
    ingredients: ['tavuk göğsü', 'jambon', 'kaşar', 'ekmek kırığı', 'yumurta', 'zeytinyağı'],
    cookingTime: 40,
    difficulty: 'zor',
    cuisine: 'Fransız',
  },
];
